services:
    app_file.metadata.file_locator:
        class: Metadata\Driver\FileLocator

    App\Bundle\FileBundle\Metadata\Driver\AnnotationDriver:
        arguments:
            - '@annotation_reader'

    app_file.metadata_driver:
        alias: app_file.metadata_driver.chain

    app_file.metadata.cache.file_cache:
        class: Metadata\Cache\FileCache

    app_file.metadata.cache:
        alias:  app_file.metadata.cache.file_cache

    app_file.metadata_factory:
        class:  Metadata\MetadataFactory
        arguments:
            - '@app_file.metadata_driver'
            - 'Metadata\ClassHierarchyMetadata'
        calls:
            - [ setCache, [ '@app_file.metadata.cache' ] ]

    App\Bundle\FileBundle\Metadata\MetadataReader:
        arguments:
            - '@app_file.metadata_factory'

    app_file.metadata_driver.chain:
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@App\Bundle\FileBundle\Metadata\Driver\AnnotationDriver']
