services:
    videni_file.metadata.file_locator:
        class: Metadata\Driver\FileLocator

    videni_file.metadata.cache.file_cache:
        class: Metadata\Cache\FileCache

    videni_file.metadata.cache:
        alias:  videni_file.metadata.cache.file_cache

    videni_file.metadata_factory:
        class:  Metadata\MetadataFactory
        arguments:
            - '@videni_file.metadata_driver'
            - 'Metadata\ClassHierarchyMetadata'
        calls:
            - [ setCache, [ '@?videni_file.metadata.cache' ] ]

    Videni\Bundle\FileBundle\Metadata\MetadataReader:
        arguments:
            - '@videni_file.metadata_factory'

    videni_file.metadata_driver.chain:
        class: Metadata\Driver\DriverChain
        arguments:
            - ['@Videni\Bundle\FileBundle\Metadata\Driver\AnnotationDriver']

    Videni\Bundle\FileBundle\Metadata\Driver\AnnotationDriver:
        arguments:
            - '@annotation_reader'

    videni_file.metadata_driver:
        alias: videni_file.metadata_driver.chain
