imports:
    - { resource: mapping.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Videni\Bundle\FileBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    Videni\Bundle\FileBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Videni\Bundle\FileBundle\EventListener\FileEventListener:
        arguments:
            - '@Videni\Bundle\FileBundle\Metadata\MetadataReader'
            - '%videni_file.asset_endpoint%'
        tags:
          - { name: 'doctrine.event_listener', event: 'prePersist', lazy: true }
          - { name: 'doctrine.event_listener', event: 'preUpdate', lazy: true }

    Videni\Bundle\FileBundle\Serializer\FileHelper:
        arguments:
            - '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            - '@vich_uploader.metadata_reader'
            - '@Videni\Bundle\FileBundle\Metadata\MetadataReader'
            - '%videni_file.asset_endpoint%'

    Videni\Bundle\FileBundle\Serializer\FileNormalizer:
        tags:
            - { name: 'jms_serializer.event_subscriber' }
