imports:
    - { resource: mapping.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Bundle\FileBundle\:
        resource: '../../{Repository,DataFixtures,Command}'

    App\Bundle\FileBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    App\Bundle\FileBundle\Serializer\FileEndpointNormalizer:
        arguments:
            - '@App\Bundle\FileBundle\Metadata\MetadataReader'
            - '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
            - '%app_file.asset_endpoint%'
        tags:
            - { name: 'serializer.normalizer', priority: 10}

    App\Bundle\FileBundle\Serializer\FileEndpointDenormalizer:
        arguments:
            - '@api_platform.serializer.normalizer.item'
            - '@App\Bundle\FileBundle\Metadata\MetadataReader'
            - '@Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
            - '%app_file.asset_endpoint%'
        tags:
            - { name: 'serializer.normalizer', priority: 10}

    app_file.file_prefix_normalizer:
        class: App\Bundle\FileBundle\Serializer\FilePathNormalizer
        arguments:
            - '@api_platform.serializer.normalizer.item'
            - '@Vich\UploaderBundle\Templating\Helper\UploaderHelper'
            - '@vich_uploader.metadata_reader'
        tags:
            - { name: 'serializer.normalizer', priority: 10}

    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: "chengdu-1"
                endpoint: "%env(MINIO_ENDPOINT)%"
                use_path_style_endpoint: true
                credentials:
                    key: "%env(MINIO_ACCESS_KEY)%"
                    secret: "%env(MINIO_SECRET_KEY)%"
