App\Bundle\FileBundle\Entity\File:
    attributes:
        id:
            groups: ['read']
        path:
            groups: ['read']
        originalName:
            groups: ['read']
        mineType:
            groups: ['read']
