acls:
    app_file_create:
        type: entity
        class: Videni\Bundle\FileBundle\Entity\File
        label: '创建文件'
        permission: 'CREATE'
        category: "file"

    app_file_view:
        type: entity
        class: Videni\Bundle\FileBundle\Entity\File
        label: '查看文件'
        permission: 'VIEW'
        category: "file"

    app_file_delete:
        type: entity
        class: Videni\Bundle\FileBundle\Entity\File
        label: '删除文件'
        permission: 'DELETE'
        category: "file"

    app_file_edit:
        type: entity
        class: Videni\Bundle\FileBundle\Entity\File
        label: '编辑文件'
        permission: 'EDIT'
        category: "file"
